#using the ubuntu ad base image
FROM alpine   

# Setting the working dir inside the container
WORKDIR /app

#coping the script file to the container
#COPY script.sh .

#making the script executable
#RUN chmod +x script.sh

#Run the script when container starts
#CMD ["./script.sh"]