services:
  mysql_db:
    container_name: mysql_con
    image: mysql
    restart: always
    #ports:
     # - "3306:30"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=newdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Hello123456
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin_con
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST : mysql_db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql_db

  django_project:
    container_name: django_con
    image: django-img
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    volumes:
    - .:/dockerdjangosetup
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - mysql_db

      
